use anyhow::Result;
use reqwest::Client;
use crate::models::{AgentsManifest, ValidationResult, EndpointCheckResult};

pub fn validate_file(path: &str) -> Result<ValidationResult> {
    let content = std::fs::read_to_string(path)
        .map_err(|_| anyhow::anyhow!("Could not read file: {}", path))?;

    validate_content(&content)
}

pub fn validate_content(content: &str) -> Result<ValidationResult> {
    let mut errors: Vec<String> = vec![];
    let mut warnings: Vec<String> = vec![];

    // Must have a # heading
    if !content.contains("# AGENTS.md") && !content.lines().any(|l| l.starts_with("# ")) {
        errors.push("Missing top-level # heading".to_string());
    }

    // Must have a description (blockquote line)
    if !content.lines().any(|l| l.starts_with("> ")) {
        warnings.push("No description blockquote found (recommended: > Your description)".to_string());
    }

    // Must have a Capabilities section
    if !content.contains("## Capabilities") {
        errors.push("Missing ## Capabilities section".to_string());
    }

    // Should have at least one capability
    if content.contains("## Capabilities") {
        let caps_count = content.matches("### `").count();
        if caps_count == 0 {
            warnings.push("Capabilities section is empty — no capabilities declared".to_string());
        }
    }

    // Endpoints section check
    if content.contains("## Endpoints") {
        // Each endpoint should have a method
        let valid_methods = ["GET", "POST", "PUT", "DELETE", "PATCH"];
        let endpoint_lines: Vec<&str> = content
            .lines()
            .filter(|l| l.starts_with("### `"))
            .collect();

        for line in &endpoint_lines {
            let has_method = valid_methods.iter().any(|m| line.contains(m));
            if !has_method {
                warnings.push(format!(
                    "Endpoint missing HTTP method: {}",
                    line.trim_start_matches("### `").trim_end_matches('`')
                ));
            }
        }
    }

    // Check for Beacon footer (soft warning)
    if !content.contains("Generated by") {
        warnings.push("Missing generator footer".to_string());
    }

    let valid = errors.is_empty();

    if valid {
        println!("   ✅ Schema valid");
    } else {
        println!("   ❌ {} error(s) found", errors.len());
    }

    if !warnings.is_empty() {
        println!("   ⚠️  {} warning(s)", warnings.len());
    }

    Ok(ValidationResult {
        valid,
        errors,
        warnings,
        endpoint_results: vec![], // filled by check_endpoints
    })
}

pub async fn check_endpoints(content: &str) -> Result<Vec<EndpointCheckResult>> {
    let client = Client::new();
    let mut results = vec![];

    // Extract base URL if declared
    let base_url = extract_base_url(content);

    // Find all endpoint lines like ### `POST /path`
    for line in content.lines() {
        if !line.starts_with("### `") {
            continue;
        }
        let inner = line.trim_start_matches("### `").trim_end_matches('`');
        let parts: Vec<&str> = inner.splitn(2, ' ').collect();
        if parts.len() != 2 {
            continue;
        }
        let method = parts[0];
        let path = parts[1];

        // Only check if we have a base URL or path is absolute
        let url = if path.starts_with("http") {
            path.to_string()
        } else if let Some(base) = &base_url {
            format!("{}{}", base.trim_end_matches('/'), path)
        } else {
            results.push(EndpointCheckResult {
                endpoint: format!("{} {}", method, path),
                reachable: false,
                status_code: None,
                error: Some("No base URL found — cannot check relative paths".to_string()),
            });
            continue;
        };

        println!("   🔍 Checking: {} {}", method, url);

        let req = match method {
            "GET" => client.get(&url),
            "POST" => client.post(&url),
            "PUT" => client.put(&url),
            "DELETE" => client.delete(&url),
            _ => client.get(&url),
        };

        match req.timeout(std::time::Duration::from_secs(5)).send().await {
            Ok(resp) => {
                let status = resp.status().as_u16();
                // 401/403 means endpoint exists but needs auth — that's reachable
                let reachable = status < 500;
                println!("   {} {} → {}", 
                    if reachable { "✅" } else { "❌" }, 
                    url, status);
                results.push(EndpointCheckResult {
                    endpoint: format!("{} {}", method, path),
                    reachable,
                    status_code: Some(status),
                    error: None,
                });
            }
            Err(e) => {
                println!("   ❌ {} → {}", url, e);
                results.push(EndpointCheckResult {
                    endpoint: format!("{} {}", method, path),
                    reachable: false,
                    status_code: None,
                    error: Some(e.to_string()),
                });
            }
        }
    }

    Ok(results)
}

fn extract_base_url(content: &str) -> Option<String> {
    // Look for lines like: **Base URL:** `https://...`
    for line in content.lines() {
        if line.to_lowercase().contains("base url") {
            if let Some(start) = line.find('`') {
                if let Some(end) = line[start + 1..].find('`') {
                    let url = &line[start + 1..start + 1 + end];
                    if url.starts_with("http") {
                        return Some(url.to_string());
                    }
                }
            }
        }
    }
    None
}